import { StyleSheet,Platform } from "react-native";
import colors from "../../constants/colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    height: Platform.OS === "ios" ? 100 : 80,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.headerBorder,
  },
  headerBlur: {
    flex: 1,
  },
  headerGradient: {
    flex: 1,
    justifyContent: "flex-end",
    paddingBottom: 12,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "500",
    color: colors.textPrimary,
  },
  headerActions: {
    flexDirection: "row",
    gap: 12,
  },
  mainTitle: {
    fontSize: 30,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 4,
    marginLeft: 20,
  },
  headerButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.buttonBackground,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollView: {
    flex: 1,
  },
  heroSection: {
    height: 320,
    marginBottom: 24,
  },
  heroCard: {
    flex: 1,
    margin: 20,
    borderRadius: 24,
    overflow: "hidden",
    elevation: 8,
    shadowColor: colors.textBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  heroBackground: {
    flex: 1,
  },
  heroBackgroundImage: {
    borderRadius: 24,
  },
  heroOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  heroContent: {
    padding: 24,
  },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.opacity.white20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  heroBadgeText: {
    fontSize: 11,
    color: colors.White,
    fontWeight: "700",
    marginLeft: 6,
    letterSpacing: 0.5,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: colors.White,
    marginBottom: 6,
    textShadowColor: colors.opacity.overlay50,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  heroSubtitle: {
    fontSize: 16,
    color: colors.opacity.white90,
    fontWeight: "500",
    marginBottom: 8,
  },
  heroDescription: {
    fontSize: 14,
    color: colors.opacity.white80,
    lineHeight: 20,
    marginBottom: 20,
  },
  heroActions: {
    flexDirection: "row",
    gap: 12,
  },
  playButton: {
    flex: 1,
    borderRadius: 25,
    overflow: "hidden",
  },
  playButtonGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 24,
    gap: 8,
  },
  playButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textBlack,
  },
  followButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 25,
    borderWidth: 1.5,
    borderColor: colors.opacity.white30,
    backgroundColor: colors.opacity.white30,
  },
  followButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textWhite,
  },
  tabBar: {
    paddingVertical: 16,
    backgroundColor: colors.White,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.imageBorder,
  },
  tabScrollContent: {
    paddingHorizontal: 20,
    gap: 8,
  },
  tabItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: colors.transparent,
    gap: 6,
  },
  activeTabItem: {
    backgroundColor: colors.accent,
  },
  tabText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  activeTabText: {
    color: colors.textWhite,
  },
  section: {
    marginBottom: 32,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  sectionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.accentButtonBackground,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.shadowBlack,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 2,
  },
  seeAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.accent,
  },
  collectionsContainer: {
    paddingHorizontal: 20,
    gap: 12,
  },
  collectionCardWrapper: {
    width: 160,
  },
  collectionCard: {
    borderRadius: 20,
    overflow: "hidden",
    elevation: 4,
    shadowColor: colors.shadowBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  collectionGradient: {
    padding: 20,
    height: 140,
    justifyContent: "space-between",
  },
  collectionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.opacity.white20,
    justifyContent: "center",
    alignItems: "center",
  },
  collectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.White,
    marginBottom: 4,
  },
  collectionDescription: {
    fontSize: 12,
    color: colors.opacity.white80,
    lineHeight: 16,
  },
  collectionFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  collectionCount: {
    fontSize: 11,
    color: colors.opacity.white80,
    fontWeight: "500",
  },
  featuredCard: {
    width: 200,
    marginRight: 16,
    backgroundColor: colors.White,
    borderRadius: 16,
    overflow: "hidden",
    elevation: 3,
    shadowColor: colors.shadowBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  featuredImageContainer: {
    position: "relative",
    height: 120,
  },
  featuredImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  featuredImageOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  newIndicator: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.borderColor,
  },
  newDot: {
    width: "100%",
    height: "100%",
    borderRadius: 4,
    backgroundColor: colors.borderColor,
  },
  featuredPlayButton: {
    position: "absolute",
    bottom: 12,
    right: 12,
    borderRadius: 16,
    overflow: "hidden",
  },
  featuredPlayGradient: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  featuredContent: {
    padding: 16,
  },
  featuredBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 8,
  },
  featuredBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.textWhite,
    letterSpacing: 0.5,
  },
  featuredTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textBlack,
    marginBottom: 4,
    lineHeight: 20,
  },
  featuredAuthor: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  featuredMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  featuredRating: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  featuredRatingText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textBlack,
  },
  featuredCategory: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  episodeCard: {
    width: 160,
    marginRight: 16,
    backgroundColor: colors.White,
    borderRadius: 12,
    overflow: "hidden",
    elevation: 2,
    shadowColor: colors.shadowBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  episodeImageContainer: {
    position: "relative",
    height: 100,
  },
  episodeImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  episodePlayButton: {
    position: "absolute",
    bottom: 8,
    right: 8,
    borderRadius: 12,
    overflow: "hidden",
  },
  episodePlayBlur: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  episodeContent: {
    padding: 12,
  },
  episodeTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textBlack,
    marginBottom: 4,
    lineHeight: 18,
  },
  episodeAuthor: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  episodeMeta: {
    flexDirection: "row",
    gap: 12,
  },
  episodeMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  episodeMetaText: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  chartsContainer: {
    paddingHorizontal: 20,
  },
  chartItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    gap: 12,
  },
  chartRankContainer: {
    position: "relative",
    width: 32,
    alignItems: "center",
  },
  chartRank: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  chartRankText: {
    fontSize: 14,
    fontWeight: "700",
  },
  hotIndicator: {
    position: "absolute",
    top: -4,
    right: -4,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.borderColor,
    justifyContent: "center",
    alignItems: "center",
  },
  chartImageContainer: {
    position: "relative",
  },
  chartImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
    resizeMode: "cover",
  },
  chartImageBorder: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderWidth: 1,
    borderRadius: 8,
  },
  chartContent: {
    flex: 1,
    justifyContent: "center",
    gap: 2,
  },
  chartTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.textBlack,
  },
  chartAuthor: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  chartMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 2,
  },
  chartCategory: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  chartStats: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  chartStatsText: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  chartActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  chartGrowth: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  chartMoreButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.buttonBackgroundSecondary,
  },
  chartSeparator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.separator,
    marginLeft: 92,
  },
  bottomSpacing: {
    height: 100,
  },
  nowPlayingBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 80,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.opacity.white10,
  },
  nowPlayingBlur: {
    flex: 1,
  },
  nowPlayingGradient: {
    flex: 1,
  },
  nowPlayingContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    gap: 12,
  },
  nowPlayingImageContainer: {
    position: "relative",
  },
  nowPlayingImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
    resizeMode: "cover",
  },
  nowPlayingImageBorder: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderWidth: 1,
    borderColor: colors.progressBackground,
    borderRadius: 8,
  },
  nowPlayingInfo: {
    flex: 1,
    justifyContent: "center",
    gap: 2,
  },
  nowPlayingTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.shadowBlack,
  },
  nowPlayingAuthor: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  nowPlayingActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  nowPlayingButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.accentButtonBackground,
  },
  nowPlayingMainButton: {
    borderRadius: 20,
    overflow: "hidden",
  },
  nowPlayingMainGradient: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
});

export default styles;